use phf::Map;
use phf_macros::phf_map;

use crate::color::style::{ColorStyle, RgbValue};
use crate::color::theme::ColorTheme;

pub(super) const BLUE_DIR: RgbValue = RgbValue::new(97, 175, 239);
pub(super) const CYAN_LINK: RgbValue = RgbValue::new(86, 182, 194);
pub(super) const GREEN_EXEC: RgbValue = RgbValue::from_hex(0x89e051);
pub(super) const RED_RO: RgbValue = RgbValue::new(224, 108, 117);
pub(super) const GRAY_DIM: RgbValue = RgbValue::from_hex(0x6d8086);

pub(super) const RUST: RgbValue = RgbValue::from_hex(0xdea584);
pub(super) const GO: RgbValue = RgbValue::from_hex(0x00add8);
pub(super) const PYTHON: RgbValue = RgbValue::from_hex(0xffbc03);
pub(super) const RUBY: RgbValue = RgbValue::from_hex(0x701516);
pub(super) const PHP: RgbValue = RgbValue::from_hex(0x8892bf);
pub(super) const LUA: RgbValue = RgbValue::from_hex(0x00a2ff);
pub(super) const C_BLUE: RgbValue = RgbValue::from_hex(0x599eff);
pub(super) const CPP: RgbValue = RgbValue::from_hex(0x519aba);
pub(super) const HEADER: RgbValue = RgbValue::from_hex(0xa074c4);
pub(super) const CS: RgbValue = RgbValue::from_hex(0x596706);
pub(super) const JAVA: RgbValue = RgbValue::from_hex(0xcc7832);
pub(super) const KOTLIN: RgbValue = RgbValue::from_hex(0x7f52ff);
pub(super) const JS: RgbValue = RgbValue::from_hex(0xcbcb41);
pub(super) const TS: RgbValue = RgbValue::from_hex(0x519aba);
pub(super) const HTML: RgbValue = RgbValue::from_hex(0xe44d26);
pub(super) const CSS: RgbValue = RgbValue::from_hex(0x663399);
pub(super) const JSON: RgbValue = RgbValue::from_hex(0xcbcb41);
pub(super) const YAML: RgbValue = RgbValue::from_hex(0xcb171e);
pub(super) const TOML: RgbValue = RgbValue::from_hex(0x9c4221);
pub(super) const XML: RgbValue = RgbValue::from_hex(0xe37933);
pub(super) const SHELL: RgbValue = GREEN_EXEC;
pub(super) const SWIFT: RgbValue = RgbValue::from_hex(0xf05138);
pub(super) const DART: RgbValue = RgbValue::from_hex(0x03589c);
pub(super) const HASKELL: RgbValue = RgbValue::from_hex(0xa074c4);
pub(super) const ELIXIR: RgbValue = RgbValue::from_hex(0xa074c4);
pub(super) const ERLANG: RgbValue = RgbValue::from_hex(0xb83998);
pub(super) const CLOJURE: RgbValue = RgbValue::from_hex(0x8dc149);
pub(super) const ZIG: RgbValue = RgbValue::from_hex(0xf69a1b);
pub(super) const VUE: RgbValue = RgbValue::from_hex(0x42b883);
pub(super) const SVELTE: RgbValue = RgbValue::from_hex(0xff3e00);
pub(super) const MARKDOWN: RgbValue = RgbValue::from_hex(0x519aba);
pub(super) const TEXT: RgbValue = RgbValue::from_hex(0xededed);
pub(super) const SQL: RgbValue = RgbValue::from_hex(0xdad8d8);
pub(super) const GRAPHQL: RgbValue = RgbValue::from_hex(0xe535ab);
pub(super) const TERRAFORM: RgbValue = RgbValue::from_hex(0x844fba);
pub(super) const CONFIG: RgbValue = GRAY_DIM;
pub(super) const ENV: RgbValue = RgbValue::from_hex(0xfaf743);
pub(super) const IMAGE: RgbValue = RgbValue::from_hex(0xa074c4);
pub(super) const AUDIO: RgbValue = RgbValue::from_hex(0x00afff);
pub(super) const VIDEO: RgbValue = RgbValue::from_hex(0xfd971f);
pub(super) const ARCHIVE: RgbValue = RgbValue::from_hex(0xeca517);
pub(super) const DOCUMENT: RgbValue = RgbValue::from_hex(0x185abd);
pub(super) const PDF: RgbValue = DOCUMENT;
pub(super) const SPREADSHEET: RgbValue = RgbValue::from_hex(0x89e051);
pub(super) const LOCK: RgbValue = RgbValue::from_hex(0x7a0d21);
pub(super) const PATCH: RgbValue = RgbValue::from_hex(0x41535b);
pub(super) const GIT: RgbValue = RgbValue::from_hex(0xf54d27);
pub(super) const DOCKER: RgbValue = RgbValue::from_hex(0x458ee6);
pub(super) const NODE: RgbValue = RgbValue::from_hex(0xe8274b);
pub(super) const PNPM: RgbValue = RgbValue::from_hex(0xf9ad02);
pub(super) const GRADLE: RgbValue = RgbValue::from_hex(0x005f87);
pub(super) const PRETTIER: RgbValue = RgbValue::from_hex(0x4285f4);
pub(super) const ESLINT: RgbValue = RgbValue::from_hex(0x4b32c3);
pub(super) const LICENSE: RgbValue = RgbValue::from_hex(0xd0bf41);
pub(super) const README: RgbValue = TEXT;
pub(super) const VITE: RgbValue = RgbValue::from_hex(0xffa800);
pub(super) const NIX: RgbValue = RgbValue::from_hex(0x7eb4f2);

const S_DIR: ColorStyle = ColorStyle::bold(BLUE_DIR);
const S_LINK: ColorStyle = ColorStyle::italic(CYAN_LINK);
const S_EXEC: ColorStyle = ColorStyle::plain(GREEN_EXEC);
const S_RO: ColorStyle = ColorStyle::bold(RED_RO);

static KIND_COLORS: Map<&str, ColorStyle> = phf_map! {
    "directory" => S_DIR,
    "symlink" => S_LINK,
    "executable" => S_EXEC,
    "readonly" => S_RO,
    "file" => ColorStyle::DEFAULT,
};

pub(crate) static EXTENSION_COLORS: Map<&str, ColorStyle> = phf_map! {
    "c" => ColorStyle::plain(C_BLUE),
    "h" => ColorStyle::plain(HEADER),
    "cpp" => ColorStyle::plain(CPP),
    "cc" => ColorStyle::plain(CPP),
    "cxx" => ColorStyle::plain(CPP),
    "hpp" => ColorStyle::plain(HEADER),
    "hxx" => ColorStyle::plain(HEADER),
    "mk" => ColorStyle::plain(GRAY_DIM),
    "cmake" => ColorStyle::plain(RgbValue::from_hex(0xdce3eb)),
    "rs" => ColorStyle::plain(RUST),
    "go" => ColorStyle::plain(GO),
    "zig" => ColorStyle::plain(ZIG),
    "nim" => ColorStyle::plain(RgbValue::from_hex(0xfff3d7)),
    "v" => ColorStyle::plain(RgbValue::from_hex(0x0c49a3)),
    "asm" => ColorStyle::plain(RgbValue::from_hex(0x0091bd)),
    "s" => ColorStyle::plain(RgbValue::from_hex(0x0091bd)),
    "S" => ColorStyle::plain(RgbValue::from_hex(0x0091bd)),
    "wasm" => ColorStyle::plain(RgbValue::from_hex(0x5c4cdb)),
    "java" => ColorStyle::plain(JAVA),
    "kt" => ColorStyle::plain(KOTLIN),
    "kts" => ColorStyle::plain(KOTLIN),
    "scala" => ColorStyle::plain(RgbValue::from_hex(0xdc322f)),
    "sc" => ColorStyle::plain(RgbValue::from_hex(0xdc322f)),
    "groovy" => ColorStyle::plain(RgbValue::from_hex(0x4a687c)),
    "cs" => ColorStyle::plain(CS),
    "fs" => ColorStyle::plain(TS),
    "fsx" => ColorStyle::plain(TS),
    "py" => ColorStyle::plain(PYTHON),
    "pyw" => ColorStyle::plain(PYTHON),
    "rb" => ColorStyle::plain(RUBY),
    "php" => ColorStyle::plain(PHP),
    "lua" => ColorStyle::plain(LUA),
    "pl" => ColorStyle::plain(RgbValue::from_hex(0x00afff)),
    "pm" => ColorStyle::plain(RgbValue::from_hex(0x00afff)),
    "r" => ColorStyle::plain(RgbValue::from_hex(0x2266ba)),
    "R" => ColorStyle::plain(RgbValue::from_hex(0x2266ba)),
    "sh" => ColorStyle::plain(SHELL),
    "bash" => ColorStyle::plain(SHELL),
    "zsh" => ColorStyle::plain(SHELL),
    "fish" => ColorStyle::plain(RgbValue::from_hex(0x4d5a5e)),
    "ps1" => ColorStyle::plain(RgbValue::from_hex(0x4d5a5e)),
    "psm1" => ColorStyle::plain(RgbValue::from_hex(0x4d5a5e)),
    "js" => ColorStyle::plain(JS),
    "mjs" => ColorStyle::plain(JS),
    "cjs" => ColorStyle::plain(JS),
    "jsx" => ColorStyle::plain(TS),
    "ts" => ColorStyle::plain(TS),
    "tsx" => ColorStyle::plain(TS),
    "vue" => ColorStyle::plain(VUE),
    "svelte" => ColorStyle::plain(SVELTE),
    "html" => ColorStyle::plain(HTML),
    "htm" => ColorStyle::plain(HTML),
    "css" => ColorStyle::plain(CSS),
    "scss" => ColorStyle::plain(CSS),
    "sass" => ColorStyle::plain(CSS),
    "less" => ColorStyle::plain(CSS),
    "svg" => ColorStyle::plain(IMAGE),
    "hs" => ColorStyle::plain(HASKELL),
    "lhs" => ColorStyle::plain(HASKELL),
    "ex" => ColorStyle::plain(ELIXIR),
    "exs" => ColorStyle::plain(ELIXIR),
    "heex" => ColorStyle::plain(ELIXIR),
    "erl" => ColorStyle::plain(ERLANG),
    "hrl" => ColorStyle::plain(ERLANG),
    "clj" => ColorStyle::plain(CLOJURE),
    "cljs" => ColorStyle::plain(CLOJURE),
    "cljc" => ColorStyle::plain(CLOJURE),
    "edn" => ColorStyle::plain(TS),
    "swift" => ColorStyle::plain(SWIFT),
    "dart" => ColorStyle::plain(DART),
    "m" => ColorStyle::plain(SWIFT),
    "mm" => ColorStyle::plain(SWIFT),
    "json" => ColorStyle::plain(JSON),
    "jsonc" => ColorStyle::plain(JSON),
    "yaml" => ColorStyle::plain(YAML),
    "yml" => ColorStyle::plain(YAML),
    "toml" => ColorStyle::plain(TOML),
    "xml" => ColorStyle::plain(XML),
    "ini" => ColorStyle::plain(CONFIG),
    "cfg" => ColorStyle::plain(CONFIG),
    "conf" => ColorStyle::plain(CONFIG),
    "env" => ColorStyle::plain(ENV),
    "sql" => ColorStyle::plain(SQL),
    "graphql" => ColorStyle::plain(GRAPHQL),
    "gql" => ColorStyle::plain(GRAPHQL),
    "tf" => ColorStyle::plain(TERRAFORM),
    "tfvars" => ColorStyle::plain(TERRAFORM),
    "prisma" => ColorStyle::plain(RgbValue::from_hex(0x5a67d8)),
    "md" => ColorStyle::plain(MARKDOWN),
    "mdx" => ColorStyle::plain(MARKDOWN),
    "txt" => ColorStyle::plain(TEXT),
    "tex" => ColorStyle::plain(MARKDOWN),
    "org" => ColorStyle::plain(MARKDOWN),
    "pdf" => ColorStyle::plain(PDF),
    "doc" => ColorStyle::plain(DOCUMENT),
    "docx" => ColorStyle::plain(DOCUMENT),
    "xls" => ColorStyle::plain(SPREADSHEET),
    "xlsx" => ColorStyle::plain(SPREADSHEET),
    "csv" => ColorStyle::plain(SPREADSHEET),
    "ppt" => ColorStyle::plain(RgbValue::from_hex(0xd24726)),
    "pptx" => ColorStyle::plain(RgbValue::from_hex(0xd24726)),
    "png" => ColorStyle::plain(IMAGE),
    "jpg" => ColorStyle::plain(IMAGE),
    "jpeg" => ColorStyle::plain(IMAGE),
    "gif" => ColorStyle::plain(IMAGE),
    "webp" => ColorStyle::plain(IMAGE),
    "bmp" => ColorStyle::plain(IMAGE),
    "ico" => ColorStyle::plain(RgbValue::from_hex(0xcbcb41)),
    "tiff" => ColorStyle::plain(IMAGE),
    "tif" => ColorStyle::plain(IMAGE),
    "avif" => ColorStyle::plain(IMAGE),
    "mp3" => ColorStyle::plain(AUDIO),
    "wav" => ColorStyle::plain(AUDIO),
    "flac" => ColorStyle::plain(RgbValue::from_hex(0x0075aa)),
    "ogg" => ColorStyle::plain(AUDIO),
    "aac" => ColorStyle::plain(AUDIO),
    "mp4" => ColorStyle::plain(VIDEO),
    "mkv" => ColorStyle::plain(VIDEO),
    "avi" => ColorStyle::plain(VIDEO),
    "mov" => ColorStyle::plain(VIDEO),
    "webm" => ColorStyle::plain(VIDEO),
    "zip" => ColorStyle::plain(ARCHIVE),
    "tar" => ColorStyle::plain(ARCHIVE),
    "gz" => ColorStyle::plain(ARCHIVE),
    "bz2" => ColorStyle::plain(ARCHIVE),
    "xz" => ColorStyle::plain(ARCHIVE),
    "7z" => ColorStyle::plain(ARCHIVE),
    "rar" => ColorStyle::plain(ARCHIVE),
    "tgz" => ColorStyle::plain(ARCHIVE),
    "lock" => ColorStyle::plain(LOCK),
    "patch" => ColorStyle::plain(PATCH),
    "diff" => ColorStyle::plain(PATCH),
    "o" => ColorStyle::plain(RED_RO),
    "out" => ColorStyle::plain(GREEN_EXEC),
    "obj" => ColorStyle::plain(RED_RO),
    "exe" => ColorStyle::plain(GREEN_EXEC),
};

pub(crate) static SPECIAL_COLORS: Map<&str, ColorStyle> = phf_map! {
    "makefile" => ColorStyle::plain(GRAY_DIM),
    "gnumakefile" => ColorStyle::plain(GRAY_DIM),
    "justfile" => ColorStyle::plain(GRAY_DIM),
    "cmakelists.txt" => ColorStyle::plain(RgbValue::from_hex(0xdce3eb)),
    "dockerfile" => ColorStyle::bold(DOCKER),
    "containerfile" => ColorStyle::bold(DOCKER),
    "docker-compose.yml" => ColorStyle::plain(DOCKER),
    "docker-compose.yaml" => ColorStyle::plain(DOCKER),
    "compose.yml" => ColorStyle::plain(DOCKER),
    "compose.yaml" => ColorStyle::plain(DOCKER),
    ".dockerignore" => ColorStyle::plain(DOCKER),
    "readme" => ColorStyle::bold(README),
    "readme.md" => ColorStyle::bold(README),
    "readme.rst" => ColorStyle::bold(README),
    "readme.txt" => ColorStyle::bold(README),
    "changelog" => ColorStyle::plain(RgbValue::from_hex(0xf8b424)),
    "changelog.md" => ColorStyle::plain(RgbValue::from_hex(0xf8b424)),
    "contributing" => ColorStyle::plain(GREEN_EXEC),
    "contributing.md" => ColorStyle::plain(GREEN_EXEC),
    "authors" => ColorStyle::plain(RgbValue::from_hex(0xa172ff)),
    "authors.txt" => ColorStyle::plain(RgbValue::from_hex(0xa172ff)),
    "codeowners" => ColorStyle::plain(RgbValue::from_hex(0xa172ff)),
    "security" => ColorStyle::plain(RgbValue::from_hex(0xbec4c9)),
    "security.md" => ColorStyle::plain(RgbValue::from_hex(0xbec4c9)),
    "license" => ColorStyle::plain(LICENSE),
    "license.md" => ColorStyle::plain(LICENSE),
    "license.txt" => ColorStyle::plain(LICENSE),
    "copying" => ColorStyle::plain(LICENSE),
    "unlicense" => ColorStyle::plain(LICENSE),
    ".gitignore" => ColorStyle::plain(GIT),
    ".gitattributes" => ColorStyle::plain(GIT),
    ".gitmodules" => ColorStyle::plain(GIT),
    ".editorconfig" => ColorStyle::plain(RgbValue::from_hex(0xfff2f2)),
    ".prettierrc" => ColorStyle::plain(PRETTIER),
    ".prettierrc.js" => ColorStyle::plain(PRETTIER),
    ".prettierrc.json" => ColorStyle::plain(PRETTIER),
    ".prettierrc.yaml" => ColorStyle::plain(PRETTIER),
    ".prettierrc.yml" => ColorStyle::plain(PRETTIER),
    ".prettierrc.toml" => ColorStyle::plain(PRETTIER),
    ".eslintrc" => ColorStyle::plain(ESLINT),
    ".eslintrc.js" => ColorStyle::plain(ESLINT),
    ".eslintrc.json" => ColorStyle::plain(ESLINT),
    ".eslintignore" => ColorStyle::plain(ESLINT),
    "eslint.config.js" => ColorStyle::plain(ESLINT),
    "eslint.config.ts" => ColorStyle::plain(ESLINT),
    ".env" => ColorStyle::plain(ENV),
    ".env.local" => ColorStyle::plain(ENV),
    ".env.example" => ColorStyle::plain(ENV),
    ".envrc" => ColorStyle::plain(ENV),
    "cargo.toml" => ColorStyle::bold(RUST),
    "cargo.lock" => ColorStyle::plain(LOCK),
    "rustfmt.toml" => ColorStyle::plain(RUST),
    "clippy.toml" => ColorStyle::plain(RUST),
    ".clippy.toml" => ColorStyle::plain(RUST),
    "package.json" => ColorStyle::bold(NODE),
    "package-lock.json" => ColorStyle::plain(LOCK),
    "yarn.lock" => ColorStyle::plain(RgbValue::from_hex(0x2c8ebb)),
    "pnpm-lock.yaml" => ColorStyle::plain(PNPM),
    "tsconfig.json" => ColorStyle::plain(TS),
    "jsconfig.json" => ColorStyle::plain(JS),
    "vite.config.js" => ColorStyle::plain(VITE),
    "vite.config.ts" => ColorStyle::plain(VITE),
    "webpack.config.js" => ColorStyle::plain(TS),
    "rollup.config.js" => ColorStyle::plain(TS),
    "go.mod" => ColorStyle::plain(GO),
    "go.sum" => ColorStyle::plain(GO),
    "go.work" => ColorStyle::plain(GO),
    "requirements.txt" => ColorStyle::plain(PYTHON),
    "pipfile" => ColorStyle::plain(PYTHON),
    "pipfile.lock" => ColorStyle::plain(LOCK),
    "pyproject.toml" => ColorStyle::plain(PYTHON),
    "setup.py" => ColorStyle::plain(PYTHON),
    "setup.cfg" => ColorStyle::plain(PYTHON),
    "gemfile" => ColorStyle::plain(RUBY),
    "gemfile.lock" => ColorStyle::plain(LOCK),
    "rakefile" => ColorStyle::plain(RUBY),
    "composer.json" => ColorStyle::plain(PHP),
    "composer.lock" => ColorStyle::plain(LOCK),
    "build.gradle" => ColorStyle::plain(GRADLE),
    "build.gradle.kts" => ColorStyle::plain(GRADLE),
    "pom.xml" => ColorStyle::plain(LOCK),
    "settings.gradle" => ColorStyle::plain(GRADLE),
    ".clang-format" => ColorStyle::plain(CONFIG),
    ".clangd" => ColorStyle::plain(CONFIG),
    ".vscode" => ColorStyle::plain(BLUE_DIR),
    "flake.nix" => ColorStyle::plain(NIX),
    "shell.nix" => ColorStyle::plain(NIX),
    "default.nix" => ColorStyle::plain(NIX),
    "vagrantfile" => ColorStyle::plain(RgbValue::from_hex(0x1563ff)),
    "procfile" => ColorStyle::plain(RgbValue::from_hex(0xa074c4)),
    "gruntfile.js" => ColorStyle::plain(RgbValue::from_hex(0xe37933)),
    "gulpfile.js" => ColorStyle::plain(RgbValue::from_hex(0xcc3e44)),
    "jenkinsfile" => ColorStyle::plain(RgbValue::from_hex(0xd33833)),
    ".gitlab-ci.yml" => ColorStyle::plain(RgbValue::from_hex(0xe24329)),
};

pub const THEME: ColorTheme = ColorTheme {
    name: "dark",
    kinds: &KIND_COLORS,
    extensions: &EXTENSION_COLORS,
    special: &SPECIAL_COLORS,
    fallback: ColorStyle::DEFAULT,
};
